# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'fbTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fbTestApp
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'FirebaseUI'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Phone'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/RemoteConfig'
    pod 'SVProgressHUD'

end
